### ISSUE TITLE
Javanese penyangga ꦀ U+A980 and cecakꦁ U+A981 appears on tarung ꦴ U+A9B4 instead of on the previous symbol.  Example: ꦀꦀ appears on o ꦎ symbol U+A98E when typing "om" [ꦎꦴꦀ] or if you type the penyangga first before tarung, it doesn't fuse [ ꦎꦀꦴ]

### ISSUE THREAD

**Issue by Apsodia** [notofonts/javanese#1]
Font
'NotoSansJavanese-Regular.ttf'.

Where the font came from, and when
https://noto-website-2.storage.googleapis.com/pkgs/NotoSansJavanese-unhinted.zip
Mar-23-18

Font Version
1.06uh

OS name and version
Android 8.0.0, Windows 10 Pro

Application name and version
Chrome, UC Browser, Multiling O keyboard, Word, etc

Issue: 
Javanese penyangga ꦀ U+A980 and cecakꦁ U+A981 appears on tarung ꦴ U+A9B4 instead of on the previous symbol.  Example: ꦀꦀ appears on o ꦎ symbol U+A98E when typing "om" [ꦎꦴꦀ],  or if you type the penyangga first before tarung, it doesn't fuse [ ꦎꦀꦴ]

The penyangga is supposed to be on the O character instead of the tarung as below:

![image](https://user-images.githubusercontent.com/37695119/37863290-f45193ee-2f96-11e8-9506-769cef14a27c.png)

Cecak ꦁ appears on tarung while it should be on the previous character. 

wong; ꦮꦺꦴꦁ

If you type cecak before tarunfg it doesnt fuse ꦮꦺꦁꦴ
Should be:

![image](https://user-images.githubusercontent.com/37695119/37873071-7b5c3578-3047-11e8-984b-62d3350721f8.png)

Also it appears that layar ꦂꦂhas the exact same problem. ꦧꦺꦴꦂ orꦧꦺꦂꦴ

And perhaps for other symbols as well. Basically, none of those should be on top of the tarungꦴ but on the main aksara (character) instead.

**Comment by simoncozens** [comment]
I believe this is now fixed, but to be honest I think I would need more test cases to be sure:

ꦮꦺꦴꦁ now puts the cecka on the wa, not the tarung:
![shape](https://user-images.githubusercontent.com/106728/188583495-caab5f63-c8de-4d0b-94d0-8fcfa3144e97.png)

layar similarly: ꦧꦺꦴꦂ
![shape](https://user-images.githubusercontent.com/106728/188583630-7805b62e-bb93-4296-bd09-caadee45b791.png)

**Comment by simoncozens** [comment]
OK, yes, I'm happy with this:

![shape](https://user-images.githubusercontent.com/106728/234861405-4d41a5ef-5737-4e00-a1fb-592bc1335fc6.png)
