### ISSUE TITLE
Problems on Pasangans on Noto Sans Javanese 

### ISSUE THREAD

**Issue by mahalisyarifuddin** [notofonts/javanese#2]
### Font 
NotoSansJavanese-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansJavanese/NotoSansJavanese-Regular.ttf
Date: 2018-12-19

### Font Version
2.000

### OS name and version
Windows 7

### Application name and version
Firefox 64.0

### Issue
There are some problems with the pasangans:

1. Example: ꦠꦶꦏꦸꦱ꧀ꦕ꧀ꦭꦸꦫꦸꦠ꧀ (Tikus clurut)
When the input is consonant + pangkon + consonant + pangkon + consonant + suku, the result is collided pasangans and suku.
![tikus clurut](https://user-images.githubusercontent.com/42148566/50212939-d557ba80-03ae-11e9-8aff-3692f9a22409.png)

2. Example: ꦩꦔꦤ꧀ꦏꦿꦸꦥꦸꦏ꧀ (Mangan krupuk)
When the input is consonant + pangkon + consonant + cakra + suku, the pasangan don't transform into pasangan with suku, and the suku is stuffed in the first consonant.
![mangan krupuk](https://user-images.githubusercontent.com/42148566/50213092-32ec0700-03af-11e9-9be2-e3256659531d.png)

**Comment by simoncozens** [comment]
The second issue is fixed. For the first issue, I think we *do* actually have a second-level la panjingan in the font, but I don't know if this is the rendering that people would actually want in this case. Maybe we should apply the second level stack, and if people wanted to split tikus / clurut they could use a space or ZWNJ.
