### ISSUE TITLE
Missing or wrong pasangan glyphs in Noto Sans Javanese

### ISSUE THREAD

**Issue by bennylin** [notofonts/javanese#4]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Several pasangan glyphs are missing, some base and subscript connection was off, and some are just wrong

### Font 
  > 'NotoSansJavanese-Regular.ttf' and 'NotoSansJavanese-Bold.ttf'

  > You can upload the problem font here unless it is a Chinese, Japanese or Korean font (these are large). --> Nope, I can't upload the ttf files
![image](https://user-images.githubusercontent.com/3002108/51395879-a141f780-1b1c-11e9-9103-cef77da79516.png)

### Where the font came from, and when
  > For example:
  >   Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansJavanese
  >   Date: 2019-01-15 (preferred format)

### Font Version
  > 2.000

### OS name and version
  > Win 10 ver 1703

### Application name and version
  > Tested in Firefox 61, Edge 40, and IE 11

### Issue
  > Pasangan "na" + "pengkal" is too similar to pasangan "nya"
  > ꦤ꧀ꦤꦾ ꦚ꧀ꦚ

### Character data
  > ꦤ+꧀+ꦚ
  > ꦤ+꧀+ꦤ+ꦾ

### Screenshot
  > 
![image](https://user-images.githubusercontent.com/3002108/51434477-c54a2980-1c3f-11e9-983f-15f0ef57a9fa.png)

**Comment by simoncozens** [comment]
This underlying issue has (I think!) been fixed:

![shape](https://user-images.githubusercontent.com/106728/188590980-865cb2ba-f3c1-4ecb-a85f-a2badc19b1b6.png)

Please let me know if I've misunderstood and I will reopen.
