### ISSUE TITLE
Problem with subscripts in Noto Sans Javanese

### ISSUE THREAD

**Issue by bennylin** [notofonts/javanese#5]
### Title 
  > Some problem with subscript glyphs combination, mainly **cakra** (U+a9bf) and **suku** (U+a9b8)

### Font 
  > 'NotoSansJavanese-Regular.ttf' and 'NotoSansJavanese-Bold.ttf'

### Where the font came from, and when
  > For example:
  >   Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansJavanese
  >   Date: 2019-01-15 (preferred format)

### Font Version
  > 2.000

### OS name and version
  > Win 10 ver 1703

### Application name and version
  > Tested in Firefox 61, Edge 40, and IE 11

### Issue
  > The combination of cakra was wrong in 5 instances

![image](https://user-images.githubusercontent.com/3002108/51434599-959d2080-1c43-11e9-841d-37d9f05ef18d.png)

  > Meanwhile, the combination of cakra with wulu is wrong in 15 instances. The suku should be on the pasangan, not on the base.

![image](https://user-images.githubusercontent.com/3002108/51434589-80c08d00-1c43-11e9-9a9a-9f3e21833c9b.png)

### Character data
  > See above. 

### Screenshot
  > Screenshot already included in the Issue

**Comment by simoncozens** [comment]
I'm really sorry, I'd like to work on this but I'm having problems reconstructing the Unicode sequences to test it. (I'm just not good enough at typing Javanese.) I think some of these are fixed, in that the suku attaches to the pasangan form in the examples I have been able to type: e.g. ꦭ꧀ꦭꦿꦸ is now
![shape](https://user-images.githubusercontent.com/106728/188594133-8618e463-c74a-4466-9dab-476eecb05bb3.png)

But if there are cases which are still broken, please paste the actual text and I can have a look.

**Comment by simoncozens** [comment]
I think this is fixed; I've heard nothing back on it, but if there are still issues please let me know and I will reopen.
