### ISSUE TITLE
Javanese: Vowel or medial consonant under pasangan too large in some cases

### ISSUE THREAD

**Issue by NorbertLindenberg** [notofonts/javanese#6]
### Font 
NotoSansJavanese-Regular.ttf

### Where the font came from, and when
https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansJavanese/NotoSansJavanese-Regular.ttf
2019-03-24

### Font Version
2.000

### OS name and version
macOS 10.13.6

### Application name and version
Safari 12.0.3
Firefox 66.0.1

### Issue
Under some pasangan, an attached vowel or medial consonant is rendered too large.

#### Steps to reproduce

Go to:
https://lindenbergsoftware.com/google/noto/java-shaping.html
and look at the section “Vowel and medial consonant under pasangan”.

#### Observed results

Suku, suku mendut, keret, and pengkal are rendered very large.

<img width="484" alt="Vowel and medial consonant under pasangan – Noto" src="https://user-images.githubusercontent.com/216206/54893094-7a33d900-4e71-11e9-9c0d-5fb6cb7caea6.png">

#### Expected results

Suku, suku mendut, keret, and pengkal should be rendered in a smaller size, as already happens when they’re placed under some other pasangan.

#### Additional information

The same test case rendered with the Yogya font, which is available as part of the Javanese Font and Keyboard app for iOS:

<img width="582" alt="Vowel and medial consonant under pasangan – Yogya" src="https://user-images.githubusercontent.com/216206/54893106-80c25080-4e71-11e9-9ac9-db668c9f41cd.png">

**Comment by simoncozens** [comment]
I've taken a look at this, and tried to implement it, but to be honest I think this is just the design.

When you say that the below marks are made smaller when placed under some other pasangans, that is true, but it's not just a question of them being made smaller; the `.ns.pas` forms of those below forms are specifically designed to connect to pasangans with straight downward strokes on the right. If you try to attach them to pasangans without a downward stroke, it all goes wrong.

![shape](https://user-images.githubusercontent.com/106728/234871358-94570dd5-3118-4a61-9bc8-0a5b029158c9.png)

So I think with this design of fonts, you just have large vowels...
