### ISSUE TITLE
Ligatures with U+A9B3 JAVANESE SIGN CECAK TELU block ligatures with U+A9BF JAVANESE CONSONANT SIGN CAKRA

### ISSUE THREAD

**Issue by dscorbett** [notofonts/javanese#7]
### Font 
NotoSansJavanese-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/3c542c9d670e518131c73c9f9f4a425ce3857aeb/unhinted/otf/NotoSansJavanese/NotoSansJavanese-Regular.otf
Date: 2022-04-25

### Font version
Version 2.003

### Issue
Ligatures between U+A9B3 JAVANESE SIGN CECAK TELU and other above-base marks block ligatures between U+A9BF JAVANESE CONSONANT SIGN CAKRA and post-base pasangan forms. Compare ⟨ꦭ꧀ꦥ꦳ꦿꦁ⟩, which is missing the ligature, to ⟨ꦭ꧀ꦥꦿꦁ⟩.

### Character data
ꦭ꧀ꦥ꦳ꦿꦁꦭ꧀ꦥꦿꦁ
U+A9AD JAVANESE LETTER LA
U+A9C0 JAVANESE PANGKON
U+A9A5 JAVANESE LETTER PA
U+A9B3 JAVANESE SIGN CECAK TELU
U+A9BF JAVANESE CONSONANT SIGN CAKRA
U+A981 JAVANESE SIGN CECAK
U+A9AD JAVANESE LETTER LA
U+A9C0 JAVANESE PANGKON
U+A9A5 JAVANESE LETTER PA
U+A9BF JAVANESE CONSONANT SIGN CAKRA
U+A981 JAVANESE SIGN CECAK

### Screenshot
![ꦭ꧀ꦥ꦳ꦿꦁꦭ꧀ꦥꦿꦁ](https://user-images.githubusercontent.com/1124347/165084087-7ae0de1b-f579-4b61-8a66-8ce620ee26ca.png)

**Comment by dscorbett** [comment]
This is still broken. The example string looks the same in version 2.004.

**Comment by simoncozens** [comment]
I've now finally fixed this:

![shape](https://github.com/notofonts/javanese/assets/106728/f6c14b55-aee8-406d-9b21-0dcdfee54d48)

Getting the marks to ligate was a fun challenge, as I hit that wonderfully obscure mark ligature rule.
