### ISSUE TITLE
Noto Sans Javanese does not support four above-base marks on one base

### ISSUE THREAD

**Issue by dscorbett** [notofonts/javanese#8]
### Font 
NotoSansJavanese-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/3c542c9d670e518131c73c9f9f4a425ce3857aeb/unhinted/otf/NotoSansJavanese/NotoSansJavanese-Regular.otf
Date: 2022-04-25

### Font version
Version 2.003

### Issue
This font supports combinations of up to three above-base marks, but not four above-base marks. The fourth mark is currently mispositioned relative to the rest and overlaps them. For example, as it supports <cecak telu, wulu, panyangga> and <wulu, panyangga, layar>, it should support the combined sequence <cecak telu, wulu, panyangga, layar>.

### Character data
ꦥ
U+A9A5 JAVANESE LETTER PA
U+A9B3 JAVANESE SIGN CECAK TELU
U+A9B6 JAVANESE VOWEL SIGN WULU
U+A980 JAVANESE SIGN PANYANGGA
U+A982 JAVANESE SIGN LAYAR

### Screenshot
![ꦥ](https://user-images.githubusercontent.com/1124347/165197319-c4f7c3d6-e4f7-4e73-a950-341e446f78e6.png)

**Comment by simoncozens** [comment]
Right. I'm going to say this is not something worth supporting unless we find an attestation. If someone finds one, we'll reopen then.
